### ISSUE TITLE
Unity lens not getting latest content

### ISSUE THREAD

**Issue by dotjorgeu** [nvbn/everpad#43] opened 2012-09-17 14:00 UTC
I see some recent notes can't be fond in the Unity lens.

See screenshot http://i.imgur.com/6RQj2.png
I search for a note title and I see the same set of notes for every search.

**Comment by ghost** [comment] 2012-09-17 16:13
I'm seeing new content, but the search does not work. No matter what I type, I see the same results. Ubuntu 12.04, 64-bit. Installed Everpad using PPA.

**Comment by hdave** [comment] 2012-09-18 13:07
Was the note that the lens couldn't find a brand new note?  Meaning:

1) Had it been previously saved locally?

2) Was it ever synced to Evernote -- can you see it on the Evernote web site?

**Comment by dotjorgeu** [comment] 2012-09-18 13:16
No matter what I search the lens shows the same notes

see 
With a keyword you can find in a note (that one should be the first one)
http://i.imgur.com/jK5PU.png 

Then with a keyword I'm sure you can't find in my notes
http://i.imgur.com/FNoHr.png

Same results

**Comment by hdave** [comment] 2012-09-21 14:33
This issue is a duplicate of #48.  I can confirm as tested/fixed in 1.9.0.

**Closed as completed** 2012-09-21 16:50 UTC
