### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by ghost** [nvbn/everpad#320] opened 2013-05-25 18:34 UTC
Unless I'm missing it, is there search functionality? If not, can this please be added?

**Comment by cengiz-io** [comment] 2013-05-30 07:27
I'm using Everpad on KDE and I can't search my notes. It seems that search functionality is dependent on Unity lens.

**Comment by zatrapilla** [comment] 2013-11-22 03:45
+1

**Comment by e2jk** [comment] 2014-01-15 22:23
Duplicate of #296.
Please close this issue to make it easier for the developers to focus by reducing noise.

**Closed as completed** 2014-01-16 01:47 UTC
