### ISSUE TITLE
Proxy setting is not read on 'Authorise'

### ISSUE THREAD

**Issue by chrisguoado** [nvbn/everpad#174] opened 2012-12-05 05:15 UTC
The http_proxy and https_proxy envs have been set before running everpad.
On clicking 'Authorise' button in the settings dialog, everpad crashed.

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 175, in change_auth
    'GET')
  File "/usr/lib/python2.7/dist-packages/oauth2/**init**.py", line 682, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/dist-packages/httplib2/**init**.py", line 1444, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1196, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1170, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 927, in connect
    raise socket.error, msg
socket.error: [Errno 113] No route to host

**Comment by fmoo** [comment] 2012-12-05 08:48
Duplicate of #156

**Closed as completed by fmoo** 2012-12-05 08:48 UTC
Labels: duplicate
