### ISSUE TITLE
xfce search note

### ISSUE THREAD

**Issue by tlhc** [nvbn/everpad#343] opened 2013-07-19 09:11 UTC
first :+1:  great job~~
when use xfce on ubuntu where shoud I search note ? would you add search bar in the main UI, thanks.. (ps: Gnome can search in panel bar..)

**Comment by DonnyBahama** [comment] 2013-09-08 21:49
Same here. Really appreciate the app, but lack of search is painful. There must be some way to search on xfce...?

**Comment by e2jk** [comment] 2014-01-15 22:23
Duplicate of #296.
Please close this issue to make it easier for the developers to focus by reducing noise.

**Closed as completed** 2020-10-11 13:00 UTC
