### ISSUE TITLE
Wrong indenting hierarchy and other format after sync

### ISSUE THREAD

**Issue by wizcas** [nvbn/everpad#155] opened 2012-11-27 15:44 UTC
The bullets list indenting works fine in the client at first, but after sync with evernote, everthing goes wrong. The hierarcy cannot be correctly maintained and other format errors occur as well, such as redundant spaces, wrong indenting of the first bullet, etc.

Hope this can be fixed soon since I have to fix the format time by time in the web version of Evernote.

**Comment by ghost** [comment] 2012-12-01 02:40
+1 same problem here

**Comment by jmoronat** [comment] 2012-12-04 01:07
Like https://github.com/nvbn/everpad/issues/135

**Comment by fmoo** [comment] 2012-12-05 16:52
Duplicate of #135

**Closed as completed by fmoo** 2012-12-05 16:52 UTC
Labels: duplicate
