### ISSUE TITLE
gnome-shell

### ISSUE THREAD

**Issue by gfavaro** [nvbn/everpad#75] opened 2012-10-04 16:44 UTC
Any plans to make it compatible with gnome3, or add an interface to search/manage notes?

**Comment by nvbn** [comment] 2012-10-04 16:57
Latest version have note management window, click to "all notes" in indicator.
I don't have plans to create integration with gnome shell, but everyone can create it using everpad-provider api. And i will merge it into repository.

**Comment by acutbal** [comment] 2012-10-08 10:05
Great!! I hadn't seen it... Growing the quality of Everpad!!

**Comment by fmoo** [comment] 2012-10-23 02:00
gnome3 support dupe of #44.

Everything else is pretty much done.

**Closed as completed** 2012-10-23 02:00 UTC
Labels: duplicate, enhancement

**Comment by flenzi** [comment] 2012-10-31 18:52
It doens't work for me in ubuntu with gnome3:
"sni-qt/9059" WARN  15:52:12.297 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE"

**Comment by fmoo** [comment] 2012-10-31 19:41
Yeah I couldn't get it working on gnome in Ubuntu either...

**Comment by nvbn** [comment] 2012-10-31 19:53
It's sni-qt bug, please create bug report for it - https://bugs.launchpad.net/sni-qt/+bugs

**Comment by nvbn** [comment] 2012-10-31 20:23
Or remove sni-qt.

**Comment by jmergy** [comment] 2012-11-26 23:37
Bummer. Unable to use Everpad. I ripped-out all things Unity and running Gnome. I am currently just running Evernote Windows under WINE >> http://mergy.org/2012/11/get-the-evernote-windows-application-on-ubuntu-12-10-via-wine/

**Comment by nvbn** [comment] 2012-12-03 01:17
For basic gnome shell support please install https://extensions.gnome.org/extension/495/topicons/

**Comment by lesliev** [comment] 2013-03-12 18:57
On gnome-shell 3.6.2-0ubuntu0.2, using the above extension worked for me. Trying to select "Black tray icon" seemed to do nothing so I did this: sudo cp /usr/share/icons/hicolor/64x64/apps/everpad-mono.png /usr/share/icons/hicolor/128x128/apps/everpad.png
Now the tray icon looks ok on a default black Gnome3 top bar.

**Comment by kendoori** [comment] 2013-05-05 13:52
@lesliev Thanks for this... your trick worked for me
