### ISSUE TITLE
Please consider support the evernote of chinese version -- Yinxiang Biji

### ISSUE THREAD

**Issue by raymonwu** [nvbn/everpad#411] opened 2014-04-26 05:13 UTC
Your soft only support Evernote International , It can't sync with the chinese version yinxiang biji.

Here is the document about how to support yinxiang biji: http://dev.evernote.com/doc/articles/bootstrap.php

Thank You!

**Comment by niu541412** [comment] 2014-04-30 18:29
如果你安装到标准的目录下的话，删除授权，
修改
/usr/share/pyshared/everpad/const.py
这个文件，把里面的
HOST = 'www.evernote.com' 那行换成
HOST = 'app.yinxiang.com'
运行点击授权就会跳转到印象笔记的授权页了，我自己的ubuntu已测试可行。

**Comment by e2jk** [comment] 2014-06-15 21:29
Hi @raymonwu , please close this issue as a duplicate of #396.

**Closed as completed** 2014-06-16 07:01 UTC
