### ISSUE TITLE
Ubuntu 12.10, Gnome 3.6, Error when trying to open existing/new note.

### ISSUE THREAD

**Issue by noisufnoc** [nvbn/everpad#160] opened 2012-11-28 19:07 UTC
Hi!

I followed the debug directions in the Readme and found this error: 

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 145, in create
    editor = self.open(note)
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 122, in open
    editor = Editor(self.app, note)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 856, in **init**
    self.init_controls()
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 884, in init_controls
    self.ui.resourceLabel, self.mark_touched,
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 699, in **init**
    self.mime = magic.open(magic.MIME_TYPE)
AttributeError: 'module' object has no attribute 'open'

Everpad version: 2.0.1
API version: 1
Schema version: 1

Installed from ppa

**Comment by nvbn** [comment] 2012-11-28 19:27
python-magic is installed from repo or pip?
And maybe it's a duplicate of #41

**Comment by noisufnoc** [comment] 2012-11-28 19:31
Damn, looks to be the same issue.  Searching > Me.

What's the preferred method of installing python-magic? 

python -c 'import magic; print magic.MIME'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'MIME'

**Comment by nvbn** [comment] 2012-11-28 19:34
Prefered method is using version from repository. But with latest version from pip it works.
For solving your problem try to reinstall python-magic.

**Comment by noisufnoc** [comment] 2012-11-28 19:43
I removed python-magic, and reinstalled from the repo and am experiencing the same error.

What version of python-magic do I need?

**Comment by nvbn** [comment] 2012-11-28 19:44
I have installed 5.11. Try to 

<pre>
pip uninstall magic
</pre>

**Comment by noisufnoc** [comment] 2012-11-28 19:49
Same issue.  

```
sudo pip uninstall python-magic
Uninstalling python-magic:
/usr/local/lib/python2.7/dist-packages/magic.py
/usr/local/lib/python2.7/dist-packages/magic.pyc
/usr/local/lib/python2.7/dist-packages/python_magic-0.4.3.egg-info
Proceed (y/n)? y
Successfully uninstalled python-magic

sudo pip install python-magic
Downloading/unpacking python-magic
Downloading python-magic-0.4.3.tar.gz
Running setup.py egg_info for package python-magic

Installing collected packages: python-magic
Running setup.py install for python-magic

Successfully installed python-magic
Cleaning up...
```

**Comment by nvbn** [comment] 2012-11-28 19:52
Hm, if you try to remove version from pip and reinstall it from repo?

**Comment by noisufnoc** [comment] 2012-11-28 19:55
That seems to have done it.  Working like a champ now.  Thanks!!

```
python -c 'import magic; print magic.MIME'
1040
```

**Comment by nvbn** [comment] 2012-11-28 19:56
Ok =)

**Closed as completed by nvbn** 2012-11-28 19:56 UTC
